sudo: false
language: scala
script:
  - sbt "++${TRAVIS_SCALA_VERSION}" "^^${SBT_VERSION}" test scripted
matrix:
  include:
  - env: SBT_VERSION="0.13.15"
    jdk: openjdk7
    scala: 2.10.6
  - env: SBT_VERSION="1.0.0-M5" # TODO 1.0.0-M6 https://github.com/sbt/sbt/issues/3245
    jdk: oraclejdk8
    scala: 2.12.2
